from __future__ import annotations

import asyncio
from abc import ABC, abstractmethod

from ..data import consts


class GenericClient(ABC):
    addresses: consts.AddressList
    msg_queue: asyncio.Queue[tuple[tuple[int, int, int, int], str]]
    ready: asyncio.Event

    @abstractmethod
    async def connect(self): ...
    @abstractmethod
    async def disconnect(self): ...
    @abstractmethod
    async def should_process_checks(self) -> bool: ...
    @abstractmethod
    async def scan_locations(self, *, shop_items: bool = False, key_rings: bool = False) -> set[int]: ...

    @abstractmethod
    async def set_flag(self, address: int, flag: int, to: bool): ...
    @abstractmethod
    async def get_flag(self, address: int, flag: int) -> bool: ...
    @abstractmethod
    async def get_objective(self, objective: int) -> bool: ...

    @abstractmethod
    async def has_any_breath(self) -> bool: ...
    @abstractmethod
    async def set_breath(self, breath_id: int): ...

    @abstractmethod
    async def get_item_count(self, address: int) -> int: ...
    @abstractmethod
    async def set_item(self, address: int, count: int): ...
    @abstractmethod
    async def enable_butterfly_jar(self): ...

    @abstractmethod
    async def add_gem_pack(self): ...

    @abstractmethod
    async def check_goal(self, goal_index: int) -> bool: ...

    @abstractmethod
    async def import_deathlink(self, mode: int): ...
    @abstractmethod
    async def export_deathlink(self) -> bool: ...

    @abstractmethod
    async def apply_patch(self, ctx): ...

    @abstractmethod
    async def update_tracker(self, ctx, items: dict[str, int]): ...

    @abstractmethod
    async def allow_realm_access(self, id: int): ...

    @abstractmethod
    async def toggle_double_gems(self, to: bool): ...
